Repository nikita-parkhomenko/address_book_bot, pull requests merged in 2024-11, with the labels that each got.

#4 feature/Add-readme-file
  README.md
Labels: feature

#2 feature/implement-upcoming-birthday-by-argument
  main.py
Labels: feature

#5 feature/Add-note-class
  main.py
Labels: feature

#6 feature/Add-note
  main.py
Labels: feature

#9 enhancement/Add-note
  main.py
Labels: enhancement

#10 feauture/add-email-as-contact-field
  main.py
Labels: feature

#14 feature/Edit-notes
  main.py
Labels: feature

#15 enhancement/Update-readme-file
  README.md
Labels: enhancement

#18 enhancement/Error-handler-improvement
  main.py
Labels: enhancement

#19 :sparkles: bugfix/fix-upcomming-birthdays
  main.py
Labels: bug

#20 feature/create-starter-table
  main.py
Labels: feature

#21 feature/Save-and-load-books-data
  .gitignore
  main.py
Labels: feature

#22 enhancement/Improvements
  main.py
Labels: enhancement

#23 enhancement/Edit-note-improvements
  main.py
Labels: enhancement

#26 enhancement/Update-readme
  README.md
Labels: enhancement

#27 feature/add-tag
  main.py
Labels: feature

#28 feature/Add-note-tags-to-list-table
  main.py
Labels: feature

#29 enhancement/Readme-updates
  README.md
Labels: enhancement
